// export const CHANGE_LANDING_SUBROUTE = 'CHANGE_LANDING_SUBROUTE';
export const GET_MENU_DATA_REQUEST = 'GET_MENU_DATA_REQUEST';
export const GET_MENU_DATA_FAILURE = 'GET_MENU_DATA_FAILURE';
export const GET_MENU_DATA_SUCCESS = 'GET_MENU_DATA_SUCCESS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_SECTION_POSITION_REQUEST = 'SET_SECTION_POSITION_REQUEST';
export const SET_SECTION_POSITION_SUCCESS = 'SET_SECTION_POSITION_SUCCESS';
export const UPDATE_LANG = 'UPDATE_LANG';