export const GET_MENU_DATA_REQUEST = 'GET_MENU_DATA_REQUEST';
export const GET_MENU_DATA_SUCCESS = 'GET_MENU_DATA_SUCCESS';
export const GET_MENU_DATA_FAILURE = 'GET_MENU_DATA_FAILURE';
export const GET_VENUE_NAMES_REQUEST = 'GET_VENUE_NAMES_REQUEST';
export const GET_VENUE_NAMES_SUCCESS = 'GET_VENUE_NAMES_SUCCESS';
export const GET_VENUE_NAMES_FAILURE = 'GET_VENUE_NAMES_FAILURE';
