export const GET_VENUE_NAMES_REQUEST = 'GET_VENUE_NAMES_REQUEST';
export const GET_VENUE_NAMES_SUCCESS = 'GET_VENUE_NAMES_SUCCESS';
export const GET_VENUE_NAMES_FAILURE = 'GET_VENUE_NAMES_FAILURE';
export const GET_VENUES_REQUEST = 'GET_VENUES_REQUEST';
export const GET_VENUES_FAILURE = 'GET_VENUES_FAILURE';
export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS';
export const CLEAR_STATE = 'CLEAR_STATE';
